export const GLOBAL_PREFIX = "PIVOTIFYJS";
export const COMPUTE_KEYWORD = `${GLOBAL_PREFIX}_COMPUTE`;
export const GROUPS_KEYWORD = `${GLOBAL_PREFIX}_GROUPS`;
export const SUMMARY_PREFIX = `${GLOBAL_PREFIX}_SUMMARY`;

export const DEFAULT_DECIMAL_PLACES = 2;
